"""`nanio install` — generate an options file and write a systemd unit.

This module is the disk-write side of the `nanio install` CLI command.
The CLI handler in `nanio.cli` parses argv and prints results; everything
that touches the filesystem lives here so it can be unit-tested in
isolation against `tmp_path`.

The install layout is intentionally minimal:

- `<prefix>/etc/nanio/options.toml` (mode 0600) — the TOML file
  consumed by `nanio serve --options`. It carries server tunables in
  `[server]` and credentials in `[[users]]`.
- `<prefix>/etc/systemd/system/nanio.service` (mode 0644) — a hardened
  systemd unit running `nanio serve --options /etc/nanio/options.toml`.
- `<prefix>/var/lib/nanio/` — the data directory referenced by the
  unit's `ReadWritePaths`. We create it best-effort so systemd's
  filesystem-namespacing doesn't trip on a missing path.

We never create system users, never run `systemctl`, and never touch
anything outside the prefix tree. Operators can fully undo a wrong
install with `rm -rf` of the listed paths.
"""

from __future__ import annotations

import logging
import os
import secrets
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from nanio.options import DEFAULT_OPTIONS_PATH

_log = logging.getLogger("nanio.install")

DEFAULT_SYSTEMD_UNIT_PATH = Path("/etc/systemd/system/nanio.service")
DEFAULT_DATA_DIR = Path("/var/lib/nanio")
DEFAULT_USER = "nanio"
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 9000
DEFAULT_REGION = "us-east-1"

_OPTIONS_MODE = 0o600
_UNIT_MODE = 0o644

# Length passed to secrets.token_urlsafe. token_urlsafe(15) yields a
# 20-character string and token_urlsafe(30) yields a 40-character string,
# loosely matching the AWS conventions for access/secret key sizes.
_ACCESS_KEY_NBYTES = 15
_SECRET_KEY_NBYTES = 30


@dataclass(slots=True)
class InstallResult:
    """Outcome of a successful `install()` call.

    The CLI handler renders this into a human-readable summary; tests
    inspect it directly.
    """

    access_key: str
    secret_key: str
    options_path: Path
    systemd_unit_path: Path
    data_dir: Path
    bin_path: Path
    user: str
    host: str
    port: int
    bin_was_guessed: bool = False
    ran_steps: list[str] = field(default_factory=list)


def generate_credentials() -> tuple[str, str]:
    """Return a fresh `(access_key, secret_key)` tuple.

    Uses `secrets.token_urlsafe`, which is the same primitive that
    `MultipartManager` uses for upload IDs.
    """
    return (
        secrets.token_urlsafe(_ACCESS_KEY_NBYTES),
        secrets.token_urlsafe(_SECRET_KEY_NBYTES),
    )


def render_options_toml(
    *,
    access_key: str,
    secret_key: str,
    data_dir: Path,
    host: str,
    port: int,
    region: str = DEFAULT_REGION,
) -> str:
    """Return the TOML body for the unified options file.

    Schema:
        [server] tunables consumed by `nanio.options.load_server_options`
        [[users]] entries consumed by `TomlFileCredentialResolver`
    """
    return (
        "# nanio options. Generated by `nanio install`.\n"
        "# Edit this file to change server settings, rotate credentials,\n"
        "# or add more users; then `systemctl restart nanio`.\n"
        "\n"
        "[server]\n"
        f'data_dir  = "{data_dir}"\n'
        f'host      = "{host}"\n'
        f"port      = {port}\n"
        f'region    = "{region}"\n'
        "\n"
        "[[users]]\n"
        f'access_key = "{access_key}"\n'
        f'secret_key = "{secret_key}"\n'
        "\n"
        "# Add more users by appending additional [[users]] tables:\n"
        "#\n"
        "# [[users]]\n"
        '# access_key = "alice"\n'
        '# secret_key = "wonderland"\n'
    )


def render_systemd_unit(
    *,
    bin_path: Path,
    options_path: Path,
    data_dir: Path,
    user: str,
) -> str:
    """Render a hardened systemd unit for nanio.

    The unit's ExecStart references the options file; host/port/region/
    workers are read from there at startup. Only `data_dir` needs to
    appear in the unit itself, because systemd's `ReadWritePaths=`
    sandboxing is configured at unit-load time, not at process start.
    """
    return f"""[Unit]
Description=nanio S3-compatible object storage server
Documentation=https://github.com/apocas/nanio
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={user}
Group={user}
ExecStart={bin_path} serve --options {options_path}
Restart=on-failure
RestartSec=5

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
ReadWritePaths={data_dir}

[Install]
WantedBy=multi-user.target
"""


def detect_bin_path() -> tuple[Path, bool]:
    """Best-guess the path to the `nanio` console-script entry point.

    Returns `(path, was_guessed)`. `was_guessed=True` means we couldn't
    find a real binary on disk and fell back to a hardcoded default
    that the operator must hand-edit before starting the service.

    Resolution order:
    1. `sys.argv[0]` if it exists, is absolute, and points at a real
       file (the normal case — pipx/uv-tool/system-pip all set this).
    2. `shutil.which("nanio")` if `nanio` is on $PATH.
    3. `/usr/local/bin/nanio` (placeholder).
    """
    argv0 = sys.argv[0] if sys.argv else ""
    if argv0:
        candidate = Path(argv0).resolve()
        if candidate.is_file() and candidate.name == "nanio":
            return candidate, False
    found = shutil.which("nanio")
    if found:
        return Path(found).resolve(), False
    return Path("/usr/local/bin/nanio"), True


def install(
    *,
    prefix: Path = Path("/"),
    data_dir: Path = DEFAULT_DATA_DIR,
    bin_path: Path | None = None,
    user: str = DEFAULT_USER,
    host: str = DEFAULT_HOST,
    port: int = DEFAULT_PORT,
    region: str = DEFAULT_REGION,
    force: bool = False,
) -> InstallResult:
    """Install nanio's systemd unit and options file.

    All write paths are joined onto `prefix`, so a tmp_path-rooted
    install is fine for tests and operators can dry-run into a scratch
    directory.

    Raises `FileExistsError` if either target file already exists and
    `force` is False; the exception's args contain the offending path
    list. The CLI handler in `nanio.cli` translates this to exit 2.
    """
    bin_was_guessed = False
    if bin_path is None:
        bin_path, bin_was_guessed = detect_bin_path()

    # Resolve paths under the prefix. We strip leading `/` from the
    # default absolute paths so `prefix / path` joins correctly.
    prefix_resolved = prefix.resolve()
    options_path = prefix_resolved / _strip_leading_slash(DEFAULT_OPTIONS_PATH)
    systemd_unit_path = prefix_resolved / _strip_leading_slash(DEFAULT_SYSTEMD_UNIT_PATH)
    data_dir_resolved = prefix_resolved / _strip_leading_slash(data_dir)

    # Refuse to clobber unless --force.
    existing = [p for p in (options_path, systemd_unit_path) if p.exists()]
    if existing and not force:
        raise FileExistsError(
            f"refusing to overwrite existing files: {', '.join(str(p) for p in existing)}"
        )

    access_key, secret_key = generate_credentials()
    options_body = render_options_toml(
        access_key=access_key,
        secret_key=secret_key,
        data_dir=data_dir,
        host=host,
        port=port,
        region=region,
    )
    unit_body = render_systemd_unit(
        bin_path=bin_path,
        options_path=DEFAULT_OPTIONS_PATH,
        data_dir=data_dir,
        user=user,
    )

    # Write everything. Parent dirs are created lazily; the data dir
    # is created best-effort so the systemd unit's ReadWritePaths
    # doesn't fail on first start.
    options_path.parent.mkdir(parents=True, exist_ok=True)
    options_path.write_text(options_body, encoding="utf-8")
    os.chmod(options_path, _OPTIONS_MODE)

    systemd_unit_path.parent.mkdir(parents=True, exist_ok=True)
    systemd_unit_path.write_text(unit_body, encoding="utf-8")
    os.chmod(systemd_unit_path, _UNIT_MODE)

    data_dir_resolved.mkdir(parents=True, exist_ok=True)

    # Run the post-install steps that require system tools. Each one is
    # best-effort — failures are logged but don't abort the install.
    ran_steps: list[str] = []
    _run_step(
        ran_steps, ["useradd", "--system", "--no-create-home", "--shell", "/usr/sbin/nologin", user]
    )
    _run_step(ran_steps, ["chown", "-R", f"{user}:{user}", str(data_dir_resolved)])
    _run_step(ran_steps, ["chown", "-R", f"{user}:{user}", str(options_path.parent)])
    _run_step(ran_steps, ["systemctl", "daemon-reload"])
    _run_step(ran_steps, ["systemctl", "enable", "--now", "nanio"])

    return InstallResult(
        access_key=access_key,
        secret_key=secret_key,
        options_path=options_path,
        systemd_unit_path=systemd_unit_path,
        data_dir=data_dir_resolved,
        bin_path=bin_path,
        user=user,
        host=host,
        port=port,
        bin_was_guessed=bin_was_guessed,
        ran_steps=ran_steps,
    )


def _run_step(ran: list[str], cmd: list[str]) -> None:
    """Run a system command, appending a description to `ran` on success.

    Failures are logged at WARNING but do not raise — `nanio install`
    is best-effort for post-install steps so operators on systems
    without systemd (containers, chroot, CI) still get the written files.
    """
    label = " ".join(cmd)
    binary = shutil.which(cmd[0])
    if binary is None:
        _log.info("skipping (not found on PATH): %s", label)
        return
    try:
        subprocess.run(
            [binary, *cmd[1:]],
            check=True,
            capture_output=True,
            text=True,
        )
        ran.append(label)
    except subprocess.CalledProcessError as exc:
        # useradd exits 9 if the user already exists — not an error.
        if cmd[0] == "useradd" and exc.returncode == 9:
            ran.append(f"{label} (user already exists)")
            return
        _log.warning("%s failed (exit %d): %s", label, exc.returncode, exc.stderr.strip())


def _strip_leading_slash(p: Path) -> Path:
    """Drop the leading `/` so `prefix / p` joins inside the prefix tree."""
    s = str(p)
    while s.startswith("/"):
        s = s[1:]
    return Path(s)
