"""Tests for `nanio install`."""

from __future__ import annotations

import os
import stat
import tomllib
from pathlib import Path

import pytest

from nanio.auth.credentials import TomlFileCredentialResolver
from nanio.cli import build_parser, main
from nanio.install import (
    detect_bin_path,
    generate_credentials,
    install,
    render_options_toml,
    render_systemd_unit,
)
from nanio.options import load_server_options

# ----------------------------------------------------------------------
# generate_credentials / render helpers
# ----------------------------------------------------------------------


def test_generate_credentials_returns_two_distinct_strings():
    ak, sk = generate_credentials()
    assert isinstance(ak, str) and isinstance(sk, str)
    assert ak != sk
    # Loose AWS-shape sanity: 20-ish access key, 40-ish secret key.
    assert 18 <= len(ak) <= 24
    assert 38 <= len(sk) <= 44


def test_generate_credentials_is_random_across_calls():
    pairs = {generate_credentials() for _ in range(20)}
    assert len(pairs) == 20


def test_render_options_toml_round_trips_through_resolvers(tmp_path):
    body = render_options_toml(
        access_key="alice",
        secret_key="wonderland",
        data_dir=Path("/var/lib/nanio"),
        host="127.0.0.1",
        port=9001,
        region="eu-west-1",
    )
    p = tmp_path / "options.toml"
    p.write_text(body)

    resolver = TomlFileCredentialResolver(p)
    assert resolver.resolve("alice") == "wonderland"
    assert resolver.resolve("bob") is None

    server = load_server_options(p)
    assert server == {
        "data_dir": "/var/lib/nanio",
        "host": "127.0.0.1",
        "port": 9001,
        "region": "eu-west-1",
    }


def test_render_options_toml_uses_default_region_when_not_passed(tmp_path):
    body = render_options_toml(
        access_key="ak",
        secret_key="sk",
        data_dir=Path("/var/lib/nanio"),
        host="0.0.0.0",
        port=9000,
    )
    p = tmp_path / "options.toml"
    p.write_text(body)
    server = load_server_options(p)
    assert server["region"] == "us-east-1"


def test_render_options_toml_includes_helper_comments():
    """The generated file documents how to add more users."""
    body = render_options_toml(
        access_key="ak",
        secret_key="sk",
        data_dir=Path("/var/lib/nanio"),
        host="0.0.0.0",
        port=9000,
    )
    assert "# Add more users" in body
    assert "# nanio options. Generated by `nanio install`." in body


def test_render_systemd_unit_substitutes_all_fields():
    unit = render_systemd_unit(
        bin_path=Path("/opt/nanio/bin/nanio"),
        options_path=Path("/etc/nanio/options.toml"),
        data_dir=Path("/srv/nanio"),
        user="customuser",
    )
    assert "ExecStart=/opt/nanio/bin/nanio serve --options /etc/nanio/options.toml" in unit
    assert "User=customuser" in unit
    assert "Group=customuser" in unit
    assert "ReadWritePaths=/srv/nanio" in unit
    assert "[Install]" in unit
    assert "WantedBy=multi-user.target" in unit
    # No --host/--port/--data-dir on the command line — those live in options.toml.
    assert "--host" not in unit
    assert "--port" not in unit
    assert "--data-dir" not in unit


# ----------------------------------------------------------------------
# detect_bin_path
# ----------------------------------------------------------------------


def test_detect_bin_path_uses_argv0_when_real(tmp_path, monkeypatch):
    fake_bin = tmp_path / "nanio"
    fake_bin.write_text("#!/bin/sh\nexec true\n")
    fake_bin.chmod(0o755)
    monkeypatch.setattr("sys.argv", [str(fake_bin)])
    path, guessed = detect_bin_path()
    assert path == fake_bin.resolve()
    assert guessed is False


def test_detect_bin_path_falls_back_to_which(tmp_path, monkeypatch):
    monkeypatch.setattr("sys.argv", [""])
    fake_bin = tmp_path / "nanio"
    fake_bin.write_text("#!/bin/sh\n")
    fake_bin.chmod(0o755)
    monkeypatch.setattr("shutil.which", lambda name: str(fake_bin) if name == "nanio" else None)
    path, guessed = detect_bin_path()
    assert path == fake_bin.resolve()
    assert guessed is False


def test_detect_bin_path_last_resort_when_nothing_found(monkeypatch):
    monkeypatch.setattr("sys.argv", [""])
    monkeypatch.setattr("shutil.which", lambda name: None)
    path, guessed = detect_bin_path()
    assert path == Path("/usr/local/bin/nanio")
    assert guessed is True


def test_detect_bin_path_argv0_not_named_nanio(tmp_path, monkeypatch):
    """argv[0] points at a real file but not named `nanio` — fall through."""
    other = tmp_path / "python"
    other.write_text("#")
    other.chmod(0o755)
    monkeypatch.setattr("sys.argv", [str(other)])
    monkeypatch.setattr("shutil.which", lambda name: None)
    _, guessed = detect_bin_path()
    assert guessed is True


# ----------------------------------------------------------------------
# install() — happy path against tmp_path
# ----------------------------------------------------------------------


def test_install_happy_path_writes_both_files(tmp_path):
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))

    assert result.options_path == (tmp_path.resolve() / "etc/nanio/options.toml")
    assert result.systemd_unit_path == (tmp_path.resolve() / "etc/systemd/system/nanio.service")
    assert result.data_dir == tmp_path.resolve() / "var/lib/nanio"

    assert result.options_path.is_file()
    assert result.systemd_unit_path.is_file()
    assert result.data_dir.is_dir()


def test_install_options_file_has_mode_0600(tmp_path):
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    mode = stat.S_IMODE(os.stat(result.options_path).st_mode)
    assert mode == 0o600


def test_install_systemd_unit_has_mode_0644(tmp_path):
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    mode = stat.S_IMODE(os.stat(result.systemd_unit_path).st_mode)
    assert mode == 0o644


def test_install_options_file_parses_through_credentials_resolver(tmp_path):
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    resolver = TomlFileCredentialResolver(result.options_path)
    assert resolver.resolve(result.access_key) == result.secret_key


def test_install_options_file_parses_through_options_loader(tmp_path):
    result = install(
        prefix=tmp_path,
        bin_path=Path("/opt/nanio"),
        host="10.0.0.1",
        port=12345,
    )
    server = load_server_options(result.options_path)
    assert server["host"] == "10.0.0.1"
    assert server["port"] == 12345
    assert server["region"] == "us-east-1"
    assert server["data_dir"] == "/var/lib/nanio"


def test_install_options_file_is_valid_toml(tmp_path):
    """Sanity-check the rendered TOML against the stdlib parser."""
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    with result.options_path.open("rb") as f:
        data = tomllib.load(f)
    assert "server" in data
    assert "users" in data
    assert isinstance(data["users"], list)
    assert data["users"][0]["access_key"] == result.access_key


def test_install_systemd_unit_references_options_file(tmp_path):
    """The unit ExecStart points at the absolute /etc/nanio/options.toml,
    not the prefixed test path — the unit will run on the real system."""
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    body = result.systemd_unit_path.read_text()
    assert "ExecStart=/opt/nanio serve --options /etc/nanio/options.toml" in body
    assert "ReadWritePaths=/var/lib/nanio" in body


def test_install_two_calls_generate_distinct_keys(tmp_path):
    r1 = install(prefix=tmp_path / "a", bin_path=Path("/opt/nanio"))
    r2 = install(prefix=tmp_path / "b", bin_path=Path("/opt/nanio"))
    assert r1.access_key != r2.access_key
    assert r1.secret_key != r2.secret_key


def test_install_records_next_steps(tmp_path):
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    assert any("systemctl daemon-reload" in step for step in result.next_steps)
    assert any("systemctl enable" in step for step in result.next_steps)
    assert any("useradd" in step for step in result.next_steps)


def test_install_custom_user_propagates_to_unit(tmp_path):
    result = install(prefix=tmp_path, bin_path=Path("/opt/nanio"), user="objectstore")
    body = result.systemd_unit_path.read_text()
    assert "User=objectstore" in body
    assert "Group=objectstore" in body


# ----------------------------------------------------------------------
# install() — clobber refusal + --force
# ----------------------------------------------------------------------


def test_install_refuses_to_clobber_options(tmp_path):
    install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    with pytest.raises(FileExistsError) as ei:
        install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    assert "options.toml" in str(ei.value)


def test_install_refuses_to_clobber_unit_file_only(tmp_path):
    """Even if only the unit exists, the install must still refuse."""
    unit_dir = tmp_path / "etc/systemd/system"
    unit_dir.mkdir(parents=True)
    (unit_dir / "nanio.service").write_text("placeholder")
    with pytest.raises(FileExistsError):
        install(prefix=tmp_path, bin_path=Path("/opt/nanio"))


def test_install_force_overwrites_existing(tmp_path):
    r1 = install(prefix=tmp_path, bin_path=Path("/opt/nanio"))
    r2 = install(prefix=tmp_path, bin_path=Path("/opt/nanio"), force=True)
    assert r1.access_key != r2.access_key
    assert r2.options_path.read_text().count(r2.access_key) == 1
    assert r1.access_key not in r2.options_path.read_text()


def test_install_auto_detects_bin_when_not_passed(tmp_path, monkeypatch):
    """install(bin_path=None) → detect_bin_path() → use the result."""
    fake_bin = tmp_path / "nanio"
    fake_bin.write_text("#!/bin/sh\n")
    fake_bin.chmod(0o755)
    monkeypatch.setattr("sys.argv", [str(fake_bin)])
    result = install(prefix=tmp_path / "install")
    assert result.bin_path == fake_bin.resolve()
    assert result.bin_was_guessed is False


# ----------------------------------------------------------------------
# CLI plumbing — _cmd_install via main()
# ----------------------------------------------------------------------


def test_cli_install_happy_path(tmp_path, capsys):
    rc = main(
        [
            "install",
            "--prefix",
            str(tmp_path),
            "--bin",
            "/opt/nanio",
        ]
    )
    assert rc == 0
    out = capsys.readouterr().out
    assert "nanio installed." in out
    assert "access_key = " in out
    assert "secret_key = " in out
    assert "systemctl daemon-reload" in out
    assert "systemctl enable" in out
    assert "http://0.0.0.0:9000" in out
    # Files exist on disk.
    assert (tmp_path / "etc/nanio/options.toml").is_file()
    assert (tmp_path / "etc/systemd/system/nanio.service").is_file()


def test_cli_install_refuses_to_clobber_returns_2(tmp_path, capsys):
    main(["install", "--prefix", str(tmp_path), "--bin", "/opt/nanio"])
    capsys.readouterr()  # drain stdout from the first run
    rc = main(["install", "--prefix", str(tmp_path), "--bin", "/opt/nanio"])
    assert rc == 2
    err = capsys.readouterr().err
    assert "refusing to overwrite" in err
    assert "--force" in err


def test_cli_install_force_overrides(tmp_path, capsys):
    main(["install", "--prefix", str(tmp_path), "--bin", "/opt/nanio"])
    capsys.readouterr()
    rc = main(
        [
            "install",
            "--prefix",
            str(tmp_path),
            "--bin",
            "/opt/nanio",
            "--force",
        ]
    )
    assert rc == 0


def test_cli_install_warns_when_bin_path_was_guessed(tmp_path, capsys, monkeypatch):
    # Force detect_bin_path to fall through to the placeholder path.
    monkeypatch.setattr("sys.argv", [""])
    monkeypatch.setattr("shutil.which", lambda name: None)
    rc = main(["install", "--prefix", str(tmp_path)])
    assert rc == 0
    out = capsys.readouterr().out
    assert "WARNING" in out
    assert "/usr/local/bin/nanio" in out


def test_cli_install_subcommand_help(capsys):
    parser = build_parser()
    with pytest.raises(SystemExit):
        parser.parse_args(["install", "--help"])
    out = capsys.readouterr().out
    assert "--prefix" in out
    assert "--data-dir" in out
    assert "--force" in out


def test_cli_install_custom_user_and_host_propagate(tmp_path, capsys):
    rc = main(
        [
            "install",
            "--prefix",
            str(tmp_path),
            "--bin",
            "/opt/nanio",
            "--user",
            "objectstore",
            "--host",
            "127.0.0.1",
            "--port",
            "8888",
        ]
    )
    assert rc == 0
    body = (tmp_path / "etc/systemd/system/nanio.service").read_text()
    assert "User=objectstore" in body
    assert "Group=objectstore" in body
    # host/port no longer appear in the unit file — they live in options.toml.
    server = load_server_options(tmp_path / "etc/nanio/options.toml")
    assert server["host"] == "127.0.0.1"
    assert server["port"] == 8888
    out = capsys.readouterr().out
    assert "http://127.0.0.1:8888" in out
